const styles = {
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 5,
    color: "#1A237E",
  },
  textEmail: {
    height: 50,
    width: 350,
    backgroundColor: "#FFFFFF",
    borderColor: "#E8EAF6",
    borderWidth: 2,
    borderRadius: 15,
    marginVertical: 10,
    paddingLeft: 10,
    fontSize: 16,
    color: "#3C4858",
    shadowColor: "#9E9E9E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  textPassword: {
    height: 50,
    width: 350,
    backgroundColor: "#FFFFFF",
    borderColor: "#E8EAF6",
    borderWidth: 2,
    borderRadius: 15,
    marginVertical: 10,
    paddingLeft: 10,
    fontSize: 16,
    color: "#3C4858",
    shadowColor: "#9E9E9E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  button: {
    height: 50,
    width: 350,
    marginVertical: 15,
    backgroundColor: "#5C6BC0",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#5C6BC0",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 5,
  },
  text: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
  },
  textForgotPassword: {
    color: "#5C6BC0",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 20,
    marginLeft: 200,
  },
  textSignUp: {
    color: "#5C6BC0",
    fontSize: 18,
    fontWeight: "600",
    marginLeft: 10,
  },
  appLogo: {
    width: 200,
    height: 200,
    borderRadius: 100,
    marginBottom: 70,
  },
  appName: {
    fontSize: 40,
    fontWeight: "700",
    marginBottom: 100,
    color: "#1A237E",
  },
  signUpContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
};

export default styles;
